---
- hosts: all
  tasks:
  
  - name: add NodeSource repository for Node.js 6
    become: yes
    become_user: root
    apt_repository: 
      repo: '{{ item }} https://deb.nodesource.com/node_6.x trusty main'
      state: present
    with_items:
      - deb
      - deb-src

  - name: Update apt cache
    become: yes
    become_user: root
    apt: update_cache=yes

  - name: Install nodejs
    become: yes
    become_user: root
    apt: pkg={{ item }} state=installed force=yes
    with_items:
      - nodejs=6*
      - build-essential